<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/5
 * Time: 16:29
 * 已审核基类
 */

namespace app\user\controller;


use app\common\exception\UserTokenException;

class Examine extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if (session(config('user_type')) == '0') {
            $data = [
                'code'  => 200,
                'status' => config('errorcode.noreview'),
                'info' => '请等待审核通过',
            ];
            throw new UserTokenException($data);
        }
    }
}